version: "3"

networks:
  room-reservation:
    driver: bridge

volumes:
  postgres_data:
    driver: local

services:
  db:
    image: postgres:13.15
    restart: always
    environment:
      POSTGRES_DB: backend_db
      POSTGRES_USER: backend_user
      POSTGRES_PASSWORD: backend_password
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - "./scripts/postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh"
    networks:
      - room-reservation

  backend-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["api"]
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    environment:
      # Overrides the .env file
      POSTGRES_CONNECTION_STRING: "postgres://backend_user:backend_password@db:5432/backend_db?sslmode=disable"
    links:
      - db
    ports:
      - "8080:8080"
    networks:
      - room-reservation
