package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.48

import (
	"context"

	"gitlab.techvify.dev/its/internship/q2-2024/project/meeting-room-reservation/meeting-room-reservation-be/ent"
	graphql1 "gitlab.techvify.dev/its/internship/q2-2024/project/meeting-room-reservation/meeting-room-reservation-be/graphql"
)

// ID is the resolver for the id field.
func (r *bookingResolver) ID(ctx context.Context, obj *ent.Booking) (string, error) {
	return obj.ID.String(), nil
}

// RoomID is the resolver for the roomID field.
func (r *bookingResolver) RoomID(ctx context.Context, obj *ent.Booking) (string, error) {
	return obj.RoomID.String(), nil
}

// UserID is the resolver for the userID field.
func (r *bookingResolver) UserID(ctx context.Context, obj *ent.Booking) (string, error) {
	return obj.UserID.String(), nil
}

// Booking returns graphql1.BookingResolver implementation.
func (r *Resolver) Booking() graphql1.BookingResolver { return &bookingResolver{r} }

type bookingResolver struct{ *Resolver }
