// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"gitlab.techvify.dev/its/internship/q2-2024/project/meeting-room-reservation/meeting-room-reservation-be/ent/booking"
	"gitlab.techvify.dev/its/internship/q2-2024/project/meeting-room-reservation/meeting-room-reservation-be/ent/office"
	"gitlab.techvify.dev/its/internship/q2-2024/project/meeting-room-reservation/meeting-room-reservation-be/ent/predicate"
	"gitlab.techvify.dev/its/internship/q2-2024/project/meeting-room-reservation/meeting-room-reservation-be/ent/room"
)

// RoomUpdate is the builder for updating Room entities.
type RoomUpdate struct {
	config
	hooks    []Hook
	mutation *RoomMutation
}

// Where appends a list predicates to the RoomUpdate builder.
func (ru *RoomUpdate) Where(ps ...predicate.Room) *RoomUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetName sets the "name" field.
func (ru *RoomUpdate) SetName(s string) *RoomUpdate {
	ru.mutation.SetName(s)
	return ru
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ru *RoomUpdate) SetNillableName(s *string) *RoomUpdate {
	if s != nil {
		ru.SetName(*s)
	}
	return ru
}

// SetColor sets the "color" field.
func (ru *RoomUpdate) SetColor(s string) *RoomUpdate {
	ru.mutation.SetColor(s)
	return ru
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (ru *RoomUpdate) SetNillableColor(s *string) *RoomUpdate {
	if s != nil {
		ru.SetColor(*s)
	}
	return ru
}

// SetFloor sets the "floor" field.
func (ru *RoomUpdate) SetFloor(s string) *RoomUpdate {
	ru.mutation.SetFloor(s)
	return ru
}

// SetNillableFloor sets the "floor" field if the given value is not nil.
func (ru *RoomUpdate) SetNillableFloor(s *string) *RoomUpdate {
	if s != nil {
		ru.SetFloor(*s)
	}
	return ru
}

// SetOfficeID sets the "office_id" field.
func (ru *RoomUpdate) SetOfficeID(u uuid.UUID) *RoomUpdate {
	ru.mutation.SetOfficeID(u)
	return ru
}

// SetNillableOfficeID sets the "office_id" field if the given value is not nil.
func (ru *RoomUpdate) SetNillableOfficeID(u *uuid.UUID) *RoomUpdate {
	if u != nil {
		ru.SetOfficeID(*u)
	}
	return ru
}

// SetDescription sets the "description" field.
func (ru *RoomUpdate) SetDescription(s string) *RoomUpdate {
	ru.mutation.SetDescription(s)
	return ru
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ru *RoomUpdate) SetNillableDescription(s *string) *RoomUpdate {
	if s != nil {
		ru.SetDescription(*s)
	}
	return ru
}

// ClearDescription clears the value of the "description" field.
func (ru *RoomUpdate) ClearDescription() *RoomUpdate {
	ru.mutation.ClearDescription()
	return ru
}

// SetImageURL sets the "image_url" field.
func (ru *RoomUpdate) SetImageURL(s string) *RoomUpdate {
	ru.mutation.SetImageURL(s)
	return ru
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (ru *RoomUpdate) SetNillableImageURL(s *string) *RoomUpdate {
	if s != nil {
		ru.SetImageURL(*s)
	}
	return ru
}

// ClearImageURL clears the value of the "image_url" field.
func (ru *RoomUpdate) ClearImageURL() *RoomUpdate {
	ru.mutation.ClearImageURL()
	return ru
}

// SetIsDeleted sets the "is_deleted" field.
func (ru *RoomUpdate) SetIsDeleted(b bool) *RoomUpdate {
	ru.mutation.SetIsDeleted(b)
	return ru
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (ru *RoomUpdate) SetNillableIsDeleted(b *bool) *RoomUpdate {
	if b != nil {
		ru.SetIsDeleted(*b)
	}
	return ru
}

// ClearIsDeleted clears the value of the "is_deleted" field.
func (ru *RoomUpdate) ClearIsDeleted() *RoomUpdate {
	ru.mutation.ClearIsDeleted()
	return ru
}

// AddBookingIDs adds the "bookings" edge to the Booking entity by IDs.
func (ru *RoomUpdate) AddBookingIDs(ids ...uuid.UUID) *RoomUpdate {
	ru.mutation.AddBookingIDs(ids...)
	return ru
}

// AddBookings adds the "bookings" edges to the Booking entity.
func (ru *RoomUpdate) AddBookings(b ...*Booking) *RoomUpdate {
	ids := make([]uuid.UUID, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return ru.AddBookingIDs(ids...)
}

// SetOffice sets the "office" edge to the Office entity.
func (ru *RoomUpdate) SetOffice(o *Office) *RoomUpdate {
	return ru.SetOfficeID(o.ID)
}

// Mutation returns the RoomMutation object of the builder.
func (ru *RoomUpdate) Mutation() *RoomMutation {
	return ru.mutation
}

// ClearBookings clears all "bookings" edges to the Booking entity.
func (ru *RoomUpdate) ClearBookings() *RoomUpdate {
	ru.mutation.ClearBookings()
	return ru
}

// RemoveBookingIDs removes the "bookings" edge to Booking entities by IDs.
func (ru *RoomUpdate) RemoveBookingIDs(ids ...uuid.UUID) *RoomUpdate {
	ru.mutation.RemoveBookingIDs(ids...)
	return ru
}

// RemoveBookings removes "bookings" edges to Booking entities.
func (ru *RoomUpdate) RemoveBookings(b ...*Booking) *RoomUpdate {
	ids := make([]uuid.UUID, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return ru.RemoveBookingIDs(ids...)
}

// ClearOffice clears the "office" edge to the Office entity.
func (ru *RoomUpdate) ClearOffice() *RoomUpdate {
	ru.mutation.ClearOffice()
	return ru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RoomUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RoomUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RoomUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RoomUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ru *RoomUpdate) check() error {
	if v, ok := ru.mutation.Name(); ok {
		if err := room.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Room.name": %w`, err)}
		}
	}
	if v, ok := ru.mutation.Color(); ok {
		if err := room.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "Room.color": %w`, err)}
		}
	}
	if v, ok := ru.mutation.Floor(); ok {
		if err := room.FloorValidator(v); err != nil {
			return &ValidationError{Name: "floor", err: fmt.Errorf(`ent: validator failed for field "Room.floor": %w`, err)}
		}
	}
	if v, ok := ru.mutation.ImageURL(); ok {
		if err := room.ImageURLValidator(v); err != nil {
			return &ValidationError{Name: "image_url", err: fmt.Errorf(`ent: validator failed for field "Room.image_url": %w`, err)}
		}
	}
	if _, ok := ru.mutation.OfficeID(); ru.mutation.OfficeCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Room.office"`)
	}
	return nil
}

func (ru *RoomUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(room.Table, room.Columns, sqlgraph.NewFieldSpec(room.FieldID, field.TypeUUID))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.Name(); ok {
		_spec.SetField(room.FieldName, field.TypeString, value)
	}
	if value, ok := ru.mutation.Color(); ok {
		_spec.SetField(room.FieldColor, field.TypeString, value)
	}
	if value, ok := ru.mutation.Floor(); ok {
		_spec.SetField(room.FieldFloor, field.TypeString, value)
	}
	if value, ok := ru.mutation.Description(); ok {
		_spec.SetField(room.FieldDescription, field.TypeString, value)
	}
	if ru.mutation.DescriptionCleared() {
		_spec.ClearField(room.FieldDescription, field.TypeString)
	}
	if value, ok := ru.mutation.ImageURL(); ok {
		_spec.SetField(room.FieldImageURL, field.TypeString, value)
	}
	if ru.mutation.ImageURLCleared() {
		_spec.ClearField(room.FieldImageURL, field.TypeString)
	}
	if value, ok := ru.mutation.IsDeleted(); ok {
		_spec.SetField(room.FieldIsDeleted, field.TypeBool, value)
	}
	if ru.mutation.IsDeletedCleared() {
		_spec.ClearField(room.FieldIsDeleted, field.TypeBool)
	}
	if ru.mutation.BookingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   room.BookingsTable,
			Columns: []string{room.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.RemovedBookingsIDs(); len(nodes) > 0 && !ru.mutation.BookingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   room.BookingsTable,
			Columns: []string{room.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.BookingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   room.BookingsTable,
			Columns: []string{room.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ru.mutation.OfficeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.OfficeTable,
			Columns: []string{room.OfficeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(office.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.OfficeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.OfficeTable,
			Columns: []string{room.OfficeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(office.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{room.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// RoomUpdateOne is the builder for updating a single Room entity.
type RoomUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RoomMutation
}

// SetName sets the "name" field.
func (ruo *RoomUpdateOne) SetName(s string) *RoomUpdateOne {
	ruo.mutation.SetName(s)
	return ruo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ruo *RoomUpdateOne) SetNillableName(s *string) *RoomUpdateOne {
	if s != nil {
		ruo.SetName(*s)
	}
	return ruo
}

// SetColor sets the "color" field.
func (ruo *RoomUpdateOne) SetColor(s string) *RoomUpdateOne {
	ruo.mutation.SetColor(s)
	return ruo
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (ruo *RoomUpdateOne) SetNillableColor(s *string) *RoomUpdateOne {
	if s != nil {
		ruo.SetColor(*s)
	}
	return ruo
}

// SetFloor sets the "floor" field.
func (ruo *RoomUpdateOne) SetFloor(s string) *RoomUpdateOne {
	ruo.mutation.SetFloor(s)
	return ruo
}

// SetNillableFloor sets the "floor" field if the given value is not nil.
func (ruo *RoomUpdateOne) SetNillableFloor(s *string) *RoomUpdateOne {
	if s != nil {
		ruo.SetFloor(*s)
	}
	return ruo
}

// SetOfficeID sets the "office_id" field.
func (ruo *RoomUpdateOne) SetOfficeID(u uuid.UUID) *RoomUpdateOne {
	ruo.mutation.SetOfficeID(u)
	return ruo
}

// SetNillableOfficeID sets the "office_id" field if the given value is not nil.
func (ruo *RoomUpdateOne) SetNillableOfficeID(u *uuid.UUID) *RoomUpdateOne {
	if u != nil {
		ruo.SetOfficeID(*u)
	}
	return ruo
}

// SetDescription sets the "description" field.
func (ruo *RoomUpdateOne) SetDescription(s string) *RoomUpdateOne {
	ruo.mutation.SetDescription(s)
	return ruo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ruo *RoomUpdateOne) SetNillableDescription(s *string) *RoomUpdateOne {
	if s != nil {
		ruo.SetDescription(*s)
	}
	return ruo
}

// ClearDescription clears the value of the "description" field.
func (ruo *RoomUpdateOne) ClearDescription() *RoomUpdateOne {
	ruo.mutation.ClearDescription()
	return ruo
}

// SetImageURL sets the "image_url" field.
func (ruo *RoomUpdateOne) SetImageURL(s string) *RoomUpdateOne {
	ruo.mutation.SetImageURL(s)
	return ruo
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (ruo *RoomUpdateOne) SetNillableImageURL(s *string) *RoomUpdateOne {
	if s != nil {
		ruo.SetImageURL(*s)
	}
	return ruo
}

// ClearImageURL clears the value of the "image_url" field.
func (ruo *RoomUpdateOne) ClearImageURL() *RoomUpdateOne {
	ruo.mutation.ClearImageURL()
	return ruo
}

// SetIsDeleted sets the "is_deleted" field.
func (ruo *RoomUpdateOne) SetIsDeleted(b bool) *RoomUpdateOne {
	ruo.mutation.SetIsDeleted(b)
	return ruo
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (ruo *RoomUpdateOne) SetNillableIsDeleted(b *bool) *RoomUpdateOne {
	if b != nil {
		ruo.SetIsDeleted(*b)
	}
	return ruo
}

// ClearIsDeleted clears the value of the "is_deleted" field.
func (ruo *RoomUpdateOne) ClearIsDeleted() *RoomUpdateOne {
	ruo.mutation.ClearIsDeleted()
	return ruo
}

// AddBookingIDs adds the "bookings" edge to the Booking entity by IDs.
func (ruo *RoomUpdateOne) AddBookingIDs(ids ...uuid.UUID) *RoomUpdateOne {
	ruo.mutation.AddBookingIDs(ids...)
	return ruo
}

// AddBookings adds the "bookings" edges to the Booking entity.
func (ruo *RoomUpdateOne) AddBookings(b ...*Booking) *RoomUpdateOne {
	ids := make([]uuid.UUID, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return ruo.AddBookingIDs(ids...)
}

// SetOffice sets the "office" edge to the Office entity.
func (ruo *RoomUpdateOne) SetOffice(o *Office) *RoomUpdateOne {
	return ruo.SetOfficeID(o.ID)
}

// Mutation returns the RoomMutation object of the builder.
func (ruo *RoomUpdateOne) Mutation() *RoomMutation {
	return ruo.mutation
}

// ClearBookings clears all "bookings" edges to the Booking entity.
func (ruo *RoomUpdateOne) ClearBookings() *RoomUpdateOne {
	ruo.mutation.ClearBookings()
	return ruo
}

// RemoveBookingIDs removes the "bookings" edge to Booking entities by IDs.
func (ruo *RoomUpdateOne) RemoveBookingIDs(ids ...uuid.UUID) *RoomUpdateOne {
	ruo.mutation.RemoveBookingIDs(ids...)
	return ruo
}

// RemoveBookings removes "bookings" edges to Booking entities.
func (ruo *RoomUpdateOne) RemoveBookings(b ...*Booking) *RoomUpdateOne {
	ids := make([]uuid.UUID, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return ruo.RemoveBookingIDs(ids...)
}

// ClearOffice clears the "office" edge to the Office entity.
func (ruo *RoomUpdateOne) ClearOffice() *RoomUpdateOne {
	ruo.mutation.ClearOffice()
	return ruo
}

// Where appends a list predicates to the RoomUpdate builder.
func (ruo *RoomUpdateOne) Where(ps ...predicate.Room) *RoomUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *RoomUpdateOne) Select(field string, fields ...string) *RoomUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Room entity.
func (ruo *RoomUpdateOne) Save(ctx context.Context) (*Room, error) {
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RoomUpdateOne) SaveX(ctx context.Context) *Room {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RoomUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RoomUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ruo *RoomUpdateOne) check() error {
	if v, ok := ruo.mutation.Name(); ok {
		if err := room.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Room.name": %w`, err)}
		}
	}
	if v, ok := ruo.mutation.Color(); ok {
		if err := room.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "Room.color": %w`, err)}
		}
	}
	if v, ok := ruo.mutation.Floor(); ok {
		if err := room.FloorValidator(v); err != nil {
			return &ValidationError{Name: "floor", err: fmt.Errorf(`ent: validator failed for field "Room.floor": %w`, err)}
		}
	}
	if v, ok := ruo.mutation.ImageURL(); ok {
		if err := room.ImageURLValidator(v); err != nil {
			return &ValidationError{Name: "image_url", err: fmt.Errorf(`ent: validator failed for field "Room.image_url": %w`, err)}
		}
	}
	if _, ok := ruo.mutation.OfficeID(); ruo.mutation.OfficeCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Room.office"`)
	}
	return nil
}

func (ruo *RoomUpdateOne) sqlSave(ctx context.Context) (_node *Room, err error) {
	if err := ruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(room.Table, room.Columns, sqlgraph.NewFieldSpec(room.FieldID, field.TypeUUID))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Room.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, room.FieldID)
		for _, f := range fields {
			if !room.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != room.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.Name(); ok {
		_spec.SetField(room.FieldName, field.TypeString, value)
	}
	if value, ok := ruo.mutation.Color(); ok {
		_spec.SetField(room.FieldColor, field.TypeString, value)
	}
	if value, ok := ruo.mutation.Floor(); ok {
		_spec.SetField(room.FieldFloor, field.TypeString, value)
	}
	if value, ok := ruo.mutation.Description(); ok {
		_spec.SetField(room.FieldDescription, field.TypeString, value)
	}
	if ruo.mutation.DescriptionCleared() {
		_spec.ClearField(room.FieldDescription, field.TypeString)
	}
	if value, ok := ruo.mutation.ImageURL(); ok {
		_spec.SetField(room.FieldImageURL, field.TypeString, value)
	}
	if ruo.mutation.ImageURLCleared() {
		_spec.ClearField(room.FieldImageURL, field.TypeString)
	}
	if value, ok := ruo.mutation.IsDeleted(); ok {
		_spec.SetField(room.FieldIsDeleted, field.TypeBool, value)
	}
	if ruo.mutation.IsDeletedCleared() {
		_spec.ClearField(room.FieldIsDeleted, field.TypeBool)
	}
	if ruo.mutation.BookingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   room.BookingsTable,
			Columns: []string{room.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.RemovedBookingsIDs(); len(nodes) > 0 && !ruo.mutation.BookingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   room.BookingsTable,
			Columns: []string{room.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.BookingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   room.BookingsTable,
			Columns: []string{room.BookingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(booking.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if ruo.mutation.OfficeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.OfficeTable,
			Columns: []string{room.OfficeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(office.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.OfficeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   room.OfficeTable,
			Columns: []string{room.OfficeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(office.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Room{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{room.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
