// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Booking is the predicate function for booking builders.
type Booking func(*sql.Selector)

// Office is the predicate function for office builders.
type Office func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserRole is the predicate function for userrole builders.
type UserRole func(*sql.Selector)
